name: 배포 및 유닛 테스트

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 유닛 테스트 및 빌드
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: 리포지토리 가져오기
      uses: actions/checkout@v4
    
    - name: JDK 17 설치
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle build를 위한 권한 부여
      run: chmod +x gradlew
      
    - name: Gradle build 실행
      run: ./gradlew build


  deploy:
    name: 도커 이미지 생성 및 배포
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
    - name: 디렉토리 이동
      run: cd ./src/main/resources
      
    - name: 도커 로그인
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: 도커 이미지 생성
      run: |
        pwd
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-server .
      
    - name: 도커 이미지 업로드
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-server
